version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" # Используем порт из .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env # Подключаем файл .env для backend
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
